
object ProguardSettings {
  val buildSettings = Seq(
    "-dontobfuscate",
    "-dontoptimize",
    "-keepattributes Signature",
    "-dontwarn scala.collection.**",
    "-dontwarn scala.collection.mutable.**",
    "-dontwarn scala.**",
    "-dontwarn org.slf4j.**",
    "-dontwarn com.squareup.okhttp.**",
    "-dontwarn org.w3c.dom.bootstrap.DOMImplementationRegistry",
    "-dontwarn javax.xml.bind.DatatypeConverter",
    "-dontwarn javax.annotation.**",
    "-dontwarn javax.inject.**",
    "-dontwarn sun.misc.Unsafe",
    "-dontwarn com.facebook.**",
    "-dontnote org.xbill.DNS.spi.DNSJavaNameServiceDescriptor",
    "-dontnote com.parse.**",
    "-dontwarn com.parse.**",
    "-dontwarn org.xbill.DNS.spi.DNSJavaNameServiceDescriptor",
    "-keep class * implements org.jivesoftware.smack.provider.IQProvider",
    "-keep class * implements org.jivesoftware.smack.provider.PacketExtensionProvider",
    "-keep class de.measite.smack.AndroidDebugger { *; }",
    "-keep class * implements org.jivesoftware.smack.initializer.SmackInitializer",
    "-keep class * extends org.jivesoftware.smack.packet.Packet",
    "-keep class org.jivesoftware.smack.XMPPConnection",
    "-keep class org.jivesoftware.smack.ReconnectionManager",
    "-keep class org.jivesoftware.smack.CustomSmackConfiguration",
    "-keep class org.jivesoftware.smackx.disco.ServiceDiscoveryManager",
    "-keep class org.jivesoftware.smackx.xhtmlim.XHTMLManager",
    "-keep class org.jivesoftware.smackx.muc.MultiUserChat",
    "-keep class org.jivesoftware.smackx.bytestreams.ibb.InBandBytestreamManager",
    "-keep class org.jivesoftware.smackx.bytestreams.socks5.Socks5BytestreamManager",
    "-keep class org.jivesoftware.smackx.filetransfer.FileTransferManager",
    "-keep class org.jivesoftware.smackx.iqlast.LastActivityManager",
    "-keep class org.jivesoftware.smackx.commands.AdHocCommandManager",
    "-keep class org.jivesoftware.smackx.ping.PingManager",
    "-keep class org.jivesoftware.smackx.privacy.PrivacyListManager",
    "-keep class org.jivesoftware.smackx.time.EntityTimeManager",
    "-keep class org.jivesoftware.smackx.vcardtemp.VCardManager",
    "-keep class org.jivesoftware.smackx.hoxt.HOXTManager",
    "-keep class org.jivesoftware.smack.SASLAuthentication",
    "-keep class org.jivesoftware.smack.** {*;}",
    "-keep class org.scaloid.common.**",
    "-keep class org.jsoup.Jsoup.** {*;}",
    "-keep class com.activeandroid.** {*;}",
    "-keep class com.thangiee.LoLWithFriends.** {*;}",
    "-keep class com.nispok.snackbar.Snackbar.** {*;}",
    "-keep class android.support.v7.graphics.Palette {*;}",
    "-keepclassmembers public class * extends com.skocken.efficientadapter.lib.viewholder.AbsViewHolder {public <init>(...);}",
    "-keepclassmembers class android.support.v7.widget.Toolbar {*;}",
    "-keepclassmembers class android.support.v7.widget.SearchView { *; }",
    "-keepclassmembers class ** {public void processHTML(**);}",
    "-keepclassmembers class ** {public static Document parse(**);}",
    "-keepclassmembers class ** {public void onEvent*(**);}"
  )
}